export const usersData = [
  {
    id: 1,
    number: "admin",
    password: "123456",
    role: "ADMIN",
  },
  {
    id: 2,
    grade: 1,
    name: "Gürkan",
    surname: "Korkmaz",
    number: "1181602697",
    password: "G123",
    role: "OGRENCI",
    lessons: [],
    requiredCredit: 15,
  },
  {
    id: 3,
    grade: 2,
    name: "Emre",
    surname: "Eke",
    number: "1181602696",
    password: "E123",
    role: "OGRENCI",
    lessons: [],
    requiredCredit: 15,
  },
  {
    id: 4,
    grade: 3,
    name: "Enis",
    surname: "Şahin",
    number: "1181602695",
    password: "E123",
    role: "OGRENCI",
    lessons: [],
    requiredCredit: 15,
  },
  {
    id: 5,
    grade: 4,
    name: "Burak",
    surname: "Güçlü",
    number: "1181602694",
    password: "B123",
    role: "OGRENCI",
    lessons: [],
    requiredCredit: 15,
  },
];
